import pytest

from qmortality import qmortality_female, qmortality_male


def test_qmortality_female():
    female_1 = qmortality_female(
        age=75,
        alcohol_cat6=0,
        b_AF=0,
        b_CCF=0,
        b_antipsychotic=0,
        b_anycancer=0,
        b_asthmacopd=0,
        b_carehome=0,
        b_corticosteroids=0,
        b_cvd=0,
        b_dementia=0,
        b_epilepsy=0,
        b_learning=0,
        b_legulcer=0,
        b_liverpancreas=0,
        b_parkinsons=0,
        b_poormobility=0,
        b_ra=0,
        b_renal=0,
        b_type1=0,
        b_type2=0,
        b_vte=0,
        bmi=40,
        c_hb=0,
        ethrisk=0,
        hes_admitprior_cat=0,
        high_lft=0,
        high_platlet=0,
        s1_appetiteloss=0,
        s1_dyspnoea=0,
        s1_weightloss=0,
        smoke_cat=0,
        surv=1,
        town=2,
    )

    assert female_1 == 1.605573

    female_2 = qmortality_female(
        age=80,
        alcohol_cat6=2,
        b_AF=1,
        b_CCF=2,
        b_antipsychotic=1,
        b_anycancer=1,
        b_asthmacopd=0,
        b_carehome=0,
        b_corticosteroids=0,
        b_cvd=0,
        b_dementia=0,
        b_epilepsy=0,
        b_learning=0,
        b_legulcer=0,
        b_liverpancreas=0,
        b_parkinsons=0,
        b_poormobility=0,
        b_ra=0,
        b_renal=0,
        b_type1=0,
        b_type2=0,
        b_vte=0,
        bmi=25,
        c_hb=0,
        ethrisk=1,
        hes_admitprior_cat=2,
        high_lft=0,
        high_platlet=1,
        s1_appetiteloss=0,
        s1_dyspnoea=0,
        s1_weightloss=1,
        smoke_cat=0,
        surv=1,
        town=3,
    )

    assert female_2 == 58.600581


def test_qmortality_male():
    male_1 = qmortality_male(
        age=70,
        alcohol_cat6=2,
        b_AF=1,
        b_CCF=2,
        b_antipsychotic=1,
        b_anycancer=0,
        b_asthmacopd=0,
        b_carehome=0,
        b_corticosteroids=0,
        b_cvd=0,
        b_dementia=1,
        b_epilepsy=1,
        b_learning=1,
        b_legulcer=0,
        b_liverpancreas=1,
        b_parkinsons=0,
        b_poormobility=0,
        b_ra=0,
        b_renal=0,
        b_type1=1,
        b_type2=0,
        b_vte=1,
        bmi=27,
        c_hb=0,
        ethrisk=1,
        hes_admitprior_cat=1,
        high_lft=0,
        high_platlet=1,
        s1_appetiteloss=0,
        s1_dyspnoea=0,
        s1_weightloss=1,
        smoke_cat=0,
        surv=1,
        town=1,
    )

    assert male_1 == 94.444450

    male_2 = qmortality_male(
        age=67,
        alcohol_cat6=1,
        b_AF=0,
        b_CCF=0,
        b_antipsychotic=0,
        b_anycancer=0,
        b_asthmacopd=1,
        b_carehome=1,
        b_corticosteroids=1,
        b_cvd=0,
        b_dementia=0,
        b_epilepsy=0,
        b_learning=0,
        b_legulcer=1,
        b_liverpancreas=0,
        b_parkinsons=1,
        b_poormobility=1,
        b_ra=0,
        b_renal=0,
        b_type1=0,
        b_type2=1,
        b_vte=0,
        bmi=22,
        c_hb=1,
        ethrisk=0,
        hes_admitprior_cat=0,
        high_lft=1,
        high_platlet=0,
        s1_appetiteloss=0,
        s1_dyspnoea=0,
        s1_weightloss=0,
        smoke_cat=1,
        surv=2,
        town=2.1,
    )

    assert male_2 == 97.928996


def test_invalid_age():
    with pytest.raises(ValueError):
        qmortality_male(
            age=50,  # Invalid age
            alcohol_cat6=2,
            b_AF=1,
            b_CCF=2,
            b_antipsychotic=1,
            b_anycancer=0,
            b_asthmacopd=0,
            b_carehome=0,
            b_corticosteroids=0,
            b_cvd=0,
            b_dementia=1,
            b_epilepsy=1,
            b_learning=1,
            b_legulcer=0,
            b_liverpancreas=1,
            b_parkinsons=0,
            b_poormobility=0,
            b_ra=0,
            b_renal=0,
            b_type1=1,
            b_type2=0,
            b_vte=1,
            bmi=27,
            c_hb=0,
            ethrisk=1,
            hes_admitprior_cat=1,
            high_lft=0,
            high_platlet=1,
            s1_appetiteloss=0,
            s1_dyspnoea=0,
            s1_weightloss=1,
            smoke_cat=0,
            surv=1,
            town=1,
        )

    with pytest.raises(ValueError):
        qmortality_female(
            age=100,  # Invalid age
            alcohol_cat6=2,
            b_AF=1,
            b_CCF=2,
            b_antipsychotic=1,
            b_anycancer=0,
            b_asthmacopd=0,
            b_carehome=0,
            b_corticosteroids=0,
            b_cvd=0,
            b_dementia=1,
            b_epilepsy=1,
            b_learning=1,
            b_legulcer=0,
            b_liverpancreas=1,
            b_parkinsons=0,
            b_poormobility=0,
            b_ra=0,
            b_renal=0,
            b_type1=1,
            b_type2=0,
            b_vte=1,
            bmi=27,
            c_hb=0,
            ethrisk=1,
            hes_admitprior_cat=1,
            high_lft=0,
            high_platlet=1,
            s1_appetiteloss=0,
            s1_dyspnoea=0,
            s1_weightloss=1,
            smoke_cat=0,
            surv=1,
            town=1,
        )
